packages:
  - apps/*
  - packages/*
  - tools/*

catalogMode: prefer

catalog:
  "@types/node": ^24
  typescript: 7.0.1-rc
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: 4.1.9
  vite-plus: latest
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    typescript: "7.0.1-rc"
    vite: "*"
    vitest: "*"
allowBuilds:
  "@embedded-postgres/linux-x64": true
  "@parcel/watcher": set this to true or false
  "@prisma/client": true
  "@prisma/engines": true
  bun: true
  esbuild: true
  pgserve: true
  prisma: true
  sharp: true
  workerd: true
